server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/clowoodive/pilot
#          basedir: target/config-repo
          default-label: main
          searchPaths: pilot-springcloudconfigserver-repo